before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "cp config/database.ci.yml config/database.yml"
  - "bundle exec rake db:create:all"
  - "bundle exec rake db:schema:load"
